
services:

##########################################
##
## network instratucture
##
##########################################

    article-magick-proxy:

        container_name: article-magick-proxy

        image: nginxproxy/nginx-proxy

        restart: unless-stopped

        ports:

            - 80:80

            - 443:443

        volumes:

            - /var/run/docker.sock:/tmp/docker.sock:ro

            - /var/docker/nginx/html:/usr/share/nginx/html

            - /var/docker/nginx/certs:/etc/nginx/certs

            - /var/docker/nginx/vhost:/etc/nginx/vhost.d

        logging:

            options:

                max-size: "10m"

                max-file: "3"

    napkin-exchange-market-letsencrypt:

        container_name: article-magick-letsencrypt

        image: jrcs/letsencrypt-nginx-proxy-companion

        restart: unless-stopped

        volumes_from:

            - article-magick-proxy

        volumes:

            - /var/run/docker.sock:/var/run/docker.sock

            - /var/docker/nginx/acme:/etc/acme.sh

        environment:

            DEFAULT_EMAIL: the.software.shinobi@gmail.com

##########################################
##
## article magick application
##
##########################################

    article-magick-api:

        container_name: article-magick-api

        image: softwareshinobi/article-magick-api

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8888:8888"

        expose:

            - "8888"

        environment:

            VIRTUAL_HOST: apis.articlemagick.softwareshinobi.digital

            LETSENCRYPT_HOST: apis.articlemagick.softwareshinobi.digital

    article-magick-web:

        container_name: article-magick-web

        image: softwareshinobi/article-magick-web

        build: 

            context: web

            dockerfile: Dockerfile

        ports:

            - "8080:80"

        expose:

            - "80"

        environment:

            VIRTUAL_HOST: articlemagick.softwareshinobi.digital

            LETSENCRYPT_HOST: articlemagick.softwareshinobi.digital

    article-magick-docs:

        container_name: article-magick-docs

        image: softwareshinobi/article-magick-docs

        build: 

            context: docs

            dockerfile: Dockerfile

        ports:

            - "8088:80"

        expose:

            - "80"

        environment:

            VIRTUAL_HOST: docs.articlemagick.softwareshinobi.digital

            LETSENCRYPT_HOST: docs.articlemagick.softwareshinobi.digital


    article-magick-links:

        container_name: article-magick-links

        image: softwareshinobi/article-magick-links

        build: 

            context: links

            dockerfile: Dockerfile

        ports:

            - "8000:80"

        expose:

            - "80"

        environment:

            VIRTUAL_HOST: links.articlemagick.softwareshinobi.digital

            LETSENCRYPT_HOST: links.articlemagick.softwareshinobi.digital
